# ==================================================================
# PUBLISH NODE.JS NPM TO GITHUB PACKAGES REUSABLE WORKFLOW
# ==================================================================
name: Publish Node NPM

run-name: ${{ github.actor }} initiated Publish Node NPM workflow

on:

    # called by another workflow
    workflow_call:
    # triggered manually
    workflow_dispatch:

        inputs:

            working-directory:
                description: ''
                required: false
                type: string
                default: ''

# cancel any previously started runs of this workflow on this branch
concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:

    publish:
        name: Publish
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ${{ inputs.working-directory }}

        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@v2.5
              with:
                  egress-policy: audit      # TODO: change to 'egress-policy: block' after a couple of runs

            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                  persist-credentials: false

            - name: Setup Node.js
              uses: actions/setup-node@v3.8
              with:
                  node-version: 16.x
                  cache: 'npm'
                  cache-dependency-path: '${{ inputs.working-directory }}/package-lock.json'

            - name: npm install
              run: npm install

            - name: npm build
              run: npm build

            - name: Create Config File
              run: |
                  echo @wenqiglantz:https://npm.pkg.github.com/ > ${{ inputs.working-directory }}/.npmrc
                  echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> ${{ inputs.working-directory }}/.npmrc

            - name: npm publish
              run: npm publish
              working-directory: ${{ inputs.working-directory }}
              env:
                  NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
